### ISSUE TITLE
Error csrf token missmatch

### ISSUE THREAD

**Issue by dwiyudirayia** [mbougarne/airlock-nuxt#1]
I still error this one, why?
![image](https://user-images.githubusercontent.com/25982113/72244620-42289d00-3621-11ea-8e3f-f64c0f844e0f.png)

**Comment by mbougarne** [comment]
I'm still working on that to see if the issue is a misconfiguration or in Airlock side? By the way, this repo just to test [Laravel/airlock](https://github.com/laravel/airlock) which mean it is just for development and testing purpose.
